### PR TITLE
Use CMake instead of Autotools

### PR DESCRIPTION
**Pull request by moleculext**
This Pull Request is a proposal to replace Autotools with CMake.

### CODE REVIEW

**Comment by sergiomb2** [comment]
Since autotools code is horrible , I tend to approve this , have you tried build it ? 
ah almost forgot, and please can you rebase it ( i think you miss one commit from the other pull request) ?

**Comment by sergiomb2** [comment]
please do one git rebase with my tree and put this commits on top ,

**Comment by moleculext** [comment]
Hi,
I've compared the generated deb file before and after the switch to CMake and the files in data/template need to be autotooled before install.

So, please wait for the data/template issue fix before merging this PR.

I'll rebase when it's ready 😃

**Comment by sergiomb2** [comment]
please do a git rebase and after one git push --force , i.e or fork my repo again and put your patches in top 
please . 

Thanks

**Comment by moleculext** [comment]
Rebase done!

**Comment by sergiomb2** [comment]
almost prefect, you have 2 logs messages doubled, is possible squash them. And pinedit builds and runs (wih cmake ) ?

**Comment by moleculext** [comment]
Sorry for the mess, I've finally squashed all commits.

Yes, pinedit builds an runs via cmake:
```
cmake .
make
make DESTDIR="path/to/install" install
```
and the deb package generation works on Debian Stretch:
```
debuild -us -uc -b
```

Hope this help!

**Pull request merged**
